app/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="detail"),
    path("add/<int:product_id>/", views.cart_add, name="add"),
    path("remove/<int:product_id>/", views.cart_remove, name="remove"),
]

app/store/models.py
from django.db import models
from modelcluster.fields import ParentalKey
from wagtail.admin.panels import FieldPanel, InlinePanel, PageChooserPanel
from wagtail.fields import RichTextField
from wagtail.models import Orderable, Page

from cart.forms import CartAddProductForm


class StoreIndexPage(Page):
    intro = RichTextField(blank=True)

    content_panels = Page.content_panels + [
        FieldPanel("intro"),
    ]

    parent_page_types = ["home.HomePage"]
    subpage_types: list[str] = [
        "store.ProductIndexPage",
    ]

    max_count = 1

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request)

        context["products"] = Product.objects.all()
        context["cart_add_product_form"] = CartAddProductForm

        return context


class ProductIndexPage(Page):

    max_count = 1
    parent_page_types = [
        "store.StoreIndexPage",
    ]
    subpage_types: list[str] = [
        "store.Book",
    ]


class Product(Page):
    image = models.ForeignKey(
        "wagtailimages.Image", on_delete=models.SET_NULL, null=True, related_name="+"
    )
    description = RichTextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)

    parent_page_types = ["store.ProductIndexPage"]
    subpage_types: list[str] = []

    content_panels = Page.content_panels + [
        FieldPanel("description", classname="full"),
        FieldPanel("price"),
        FieldPanel("available"),
        FieldPanel("image"),
    ]

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request)

        context["cart_add_product_form"] = CartAddProductForm

        return context


class Book(Product):
    content_panels = Product.content_panels + [
        InlinePanel(
            "authors",
            heading="Authors",
            help_text="Select one or more authors, who contributed to this article",
        ),
    ]
    parent_page_types = [
        "store.ProductIndexPage",
    ]
    subpage_types: list[str] = []


class BookAuthor(Orderable):
    book = ParentalKey(
        "store.Book",
        null=True,
        on_delete=models.CASCADE,
        related_name="authors",
    )
    author = models.ForeignKey(
        "wagtailcore.Page",
        null=True,
        on_delete=models.CASCADE,
        related_name="books_authored",
    )

    panels = [
        PageChooserPanel(
            "author", ["contact.Person", "contact.Meeting", "contact.Organization"]
        )
    ]

app/store/templates/store/add_to_cart.html
<form
    action="{% url "cart:add" product.id %}"
    method="post"
    class="form-inline">

    {% csrf_token %}

    <input
        type="hidden"
        name="update"
        value="False"
        id="update">

    <div class="form-group">
        <label
            for="quantity"
            id="quantityLabel"
        >
            Quantity:
        </label>

        <div class="input-group">
            <input
                type="number"
                name="quantity"
                required=""
                value="1"
                min="1"
                id="quantity"
                aria-describedby="quantityLabel"
                class="form-control ms-2">

            <div class="input-group-append">
                <input
                    type="submit"
                    value="Add to cart"
                    class="btn btn-outline-primary ms-2"
                >
            </div>
        </div>
    </div>
</form>

app/store/templates/store/book.html
{% extends "base.html" %}

{% load wagtailcore_tags wagtailimages_tags %}

{% block content %}
    <h1>{{ page.title }}</h1>

    Authored by:
    {% for author in page.authors.all %}
        <a href="{% pageurl author.author %}">{{ author.author }}</a>{% if not forloop.last %},{% endif %}
    {% endfor %}

    {{ page.description | richtext }}

    {% image page.image max-320x200 %}

    <p>
        Price: ${{ page.price }}
    </p>

    <form
        action="{% url "cart:add" page.id %}"
        method="post"
        class="form-inline">

        {% csrf_token %}

        <input
            type="hidden"
            name="update"
            value="False"
            id="update">

        <div class="form-group">
            <label
                for="quantity"
                id="quantityLabel"
            >
                Quantity:
            </label>

            <div class="input-group">
                <input
                    type="number"
                    name="quantity"
                    required=""
                    value="1"
                    min="1"
                    id="quantity"
                    aria-describedby="quantityLabel"
                    class="form-control ms-2">

                <div class="input-group-append">
                    <input
                        type="submit"
                        value="Add to cart"
                        class="btn btn-outline-primary ms-2"
                    >
                </div>
            </div>
        </div>
    </form>
{% endblock %}

app/store/templates/store/inspect_order.html
{% extends "modeladmin/inspect.html" %}

{% block fields_output %}
    {% for field in fields %}
        <dt class="{{ field.type|lower }}">{{ field.label }}</dt>

        {% if field.label == "Items"%}
            <ul>
                {% for order_item in instance.items.all %}
                    <li>
                        {{ order_item }}
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <dd>{{ field.value }}</dd>
        {% endif %}
    {% endfor %}
{% endblock fields_output %}

app/store/templates/store/product.html
{% extends "base.html" %}

{% load wagtailcore_tags wagtailimages_tags %}

{% block content %}
    <h1>{{ page.title }}</h1>

    {{ page.description | richtext }}

    {% image page.image max-320x200 %}

    <p>
        Price: ${{ page.price }}
    </p>

    {% include "store/add_to_cart.html" with product=page %}
{% endblock %}

app/store/templates/store/store_index_page.html
{% extends "base.html" %}

{% load wagtailcore_tags wagtailimages_tags %}

{% block content %}
    <h1>{{ page.title }}</h1>
    {{ page.intro | richtext }}

    {% if products.count %}
        {% for product in products.all %}
            <div class="card mb-2">
                <div class="card-body">
                    <h2>
                        <a href="{% pageurl product %}">
                            {{ product }}
                        </a>
                    </h2>
                    <div class="container">
                        <div class="row">
                            <div class="col-2">
                                {% image product.image max-150x150 class="float-left me-2" %}
                            </div>
                            <div class="col">
                                {{ product.description | richtext | truncatewords_html:30 }}
                            </div>

                        </div>
                    </div>





                    <p>
                        Price ${{ product.price }}
                    </p>

                    {% include "store/add_to_cart.html" %}
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No products available</p>
    {% endif %}
{% endblock %}